name: Docker Image CI

on:
  push:
    branches: [ "docker-setup" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          file: examples/python-web-app/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-webapp:latest
          
    


